---
- name: Checking instance status
# =========================================
  hosts: streisand_host
  gather_facts: no

  remote_user: "root"
  become: true

  tasks:
    - name: use the built-in wait_for module to wait for cloud-init to complete
      ansible.builtin.wait_for:
        path: /var/lib/cloud/instance/boot-finished
...
