---
- name: Provision the DigitalOcean Server
# =======================================
  hosts: localhost
  connection: local
  gather_facts: yes

  vars:
    regions:
      "1":  "ams2"
      "2":  "ams3"
      "3":  "blr1"
      "4":  "fra1"
      "5":  "lon1"
      "6":  "nyc1"
      "7":  "nyc2"
      "8":  "nyc3"
      "9":  "sfo1"
      "10": "sfo2"
      "11": "sgp1"
      "12": "tor1"
    do_region: "8"
    do_server_name: strsnd

    do_ssh_name: streisand

  roles:
    - genesis-digitalocean

- import_playbook: ssh-setup.yml
- import_playbook: cloud-status.yml
- import_playbook: streisand.yml
...
